// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAiuT0tVgBLETMvq9z6N6esj2e058usg',
    appId: '1:66487788584:web:8a8b0c73033b09dd96411d',
    messagingSenderId: '66487788584',
    projectId: 'ciaotalk',
    authDomain: 'ciaotalk.firebaseapp.com',
    storageBucket: 'ciaotalk.appspot.com',
    measurementId: 'G-0RWK2W46N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu7lPIZEkHEUi3QwolsWRhtFf2s4lh57c',
    appId: '1:66487788584:android:2e94c814ef4ded7c96411d',
    messagingSenderId: '66487788584',
    projectId: 'ciaotalk',
    databaseURL: 'https://ciaotalk-default-rtdb.firebaseio.com',
    storageBucket: 'ciaotalk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVsPeFsAEd6icq-CxuXmZSxY_iGekPl9g',
    appId: '1:66487788584:ios:40f6a69e7b58df5396411d',
    messagingSenderId: '66487788584',
    projectId: 'ciaotalk',
    databaseURL: 'https://ciaotalk-default-rtdb.firebaseio.com',
    storageBucket: 'ciaotalk.appspot.com',
    iosClientId: '66487788584-rvhl4qm8eq4nf9lfc32t6monumadiei8.apps.googleusercontent.com',
    iosBundleId: 'com.HolaTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVsPeFsAEd6icq-CxuXmZSxY_iGekPl9g',
    appId: '1:66487788584:ios:5146bb630fef9fdc96411d',
    messagingSenderId: '66487788584',
    projectId: 'ciaotalk',
    storageBucket: 'ciaotalk.appspot.com',
    iosClientId: '66487788584-r9diuj3ejkt8me4p7enh0pbo0q6b546d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJAiuT0tVgBLETMvq9z6N6esj2e058usg',
    appId: '1:66487788584:web:89ea2e226dd8ae8296411d',
    messagingSenderId: '66487788584',
    projectId: 'ciaotalk',
    authDomain: 'ciaotalk.firebaseapp.com',
    storageBucket: 'ciaotalk.appspot.com',
    measurementId: 'G-T2T68E0N0X',
  );
}