import 'package:flutter/material.dart';

class Country {
  final String name;
  final String flag;

  Country(this.name, this.flag);
}

List<Country> countries = [
  Country('Afghanistan', '🇦🇫'),
  Country('Albania', '🇦🇱'),
  Country('Algeria', '🇩🇿'),
  Country('Andorra', '🇦🇩'),
  Country('Angola', '🇦🇴'),
  Country('Antigua and Barbuda', '🇦🇬'),
  Country('Argentina', '🇦🇷'),
  Country('Armenia', '🇦🇲'),
  Country('Australia', '🇦🇺'),
  Country('Austria', '🇦🇹'),
  Country('Azerbaijan', '🇦🇿'),
  Country('Bahamas', '🇧🇸'),
  Country('Bahrain', '🇧🇭'),
  Country('Bangladesh', '🇧🇩'),
  Country('Barbados', '🇧🇧'),
  Country('Belarus', '🇧🇾'),
  Country('Belgium', '🇧🇪'),
  Country('Belize', '🇧🇿'),
  Country('Benin', '🇧🇯'),
  Country('Bhutan', '🇧🇹'),
  Country('Bolivia', '🇧🇴'),
  Country('Bosnia and Herzegovina', '🇧🇦'),
  Country('Botswana', '🇧🇼'),
  Country('Brazil', '🇧🇷'),
  Country('Brunei', '🇧🇳'),
  Country('Bulgaria', '🇧🇬'),
  Country('Burkina Faso', '🇧🇫'),
  Country('Burundi', '🇧🇮'),
  Country('Cabo Verde', '🇨🇻'),
  Country('Cambodia', '🇰🇭'),
  Country('Cameroon', '🇨🇲'),
  Country('Canada', '🇨🇦'),
  Country('Central African Republic', '🇨🇫'),
  Country('Chad', '🇹🇩'),
  Country('Chile', '🇨🇱'),
  Country('China', '🇨🇳'),
  Country('Colombia', '🇨🇴'),
  Country('Comoros', '🇰🇲'),
  Country('Congo, Democratic Republic of the', '🇨🇩'),
  Country('Congo, Republic of the', '🇨🇬'),
  Country('Costa Rica', '🇨🇷'),
  Country('Croatia', '🇭🇷'),
  Country('Cuba', '🇨🇺'),
  Country('Cyprus', '🇨🇾'),
  Country('Czech Republic', '🇨🇿'),
  Country('Denmark', '🇩🇰'),
  Country('Djibouti', '🇩🇯'),
  Country('Dominica', '🇩🇲'),
  Country('Dominican Republic', '🇩🇴'),
  Country('Ecuador', '🇪🇨'),
  Country('Egypt', '🇪🇬'),
  Country('El Salvador', '🇸🇻'),
  Country('Equatorial Guinea', '🇬🇶'),
  Country('Eritrea', '🇪🇷'),
  Country('Estonia', '🇪🇪'),
  Country('Eswatini', '🇸🇿'),
  Country('Ethiopia', '🇪🇹'),
  Country('Fiji', '🇫🇯'),
  Country('Finland', '🇫🇮'),
  Country('France', '🇫🇷'),
  Country('Gabon', '🇬🇦'),
  Country('Gambia', '🇬🇲'),
  Country('Georgia', '🇬🇪'),
  Country('Germany', '🇩🇪'),
  Country('Ghana', '🇬🇭'),
  Country('Greece', '🇬🇷'),
  Country('Grenada', '🇬🇩'),
  Country('Guatemala', '🇬🇹'),
  Country('Guinea', '🇬🇳'),
  Country('Guinea-Bissau', '🇬🇼'),
  Country('Guyana', '🇬🇾'),
  Country('Haiti', '🇭🇹'),
  Country('Honduras', '🇭🇳'),
  Country('Hungary', '🇭🇺'),
  Country('Iceland', '🇮🇸'),
  Country('India', '🇮🇳'),
  Country('Indonesia', '🇮🇩'),
  Country('Iran', '🇮🇷'),
  Country('Iraq', '🇮🇶'),
  Country('Ireland', '🇮🇪'),
  Country('Israel', '🇮🇱'),
  Country('Italy', '🇮🇹'),
  Country('Jamaica', '🇯🇲'),
  Country('Japan', '🇯🇵'),
  Country('Jordan', '🇯🇴'),
  Country('Kazakhstan', '🇰🇿'),
  Country('Kenya', '🇰🇪'),
  Country('Kiribati', '🇰🇮'),
  Country('Korea, North', '🇰🇵'),
  Country('Korea, South', '🇰🇷'),
  Country('Kuwait', '🇰🇼'),
  Country('Kyrgyzstan', '🇰🇬'),
  Country('Laos', '🇱🇦'),
  Country('Latvia', '🇱🇻'),
  Country('Lebanon', '🇱🇧'),
  Country('Lesotho', '🇱🇸'),
  Country('Liberia', '🇱🇷'),
  Country('Libya', '🇱🇾'),
  Country('Liechtenstein', '🇱🇮'),
  Country('Lithuania', '🇱🇹'),
  Country('Luxembourg', '🇱🇺'),
  Country('Madagascar', '🇲🇬'),
  Country('Malawi', '🇲🇼'),
  Country('Malaysia', '🇲🇾'),
  Country('Maldives', '🇲🇻'),
  Country('Mali', '🇲🇱'),
  Country('Malta', '🇲🇹'),
  Country('Marshall Islands', '🇲🇭'),
  Country('Mauritania', '🇲🇷'),
  Country('Mauritius', '🇲🇺'),
  Country('Mexico', '🇲🇽'),
  Country('Micronesia', '🇫🇲'),
  Country('Moldova', '🇲🇩'),
  Country('Monaco', '🇲🇨'),
  Country('Mongolia', '🇲🇳'),
  Country('Montenegro', '🇲🇪'),
  Country('Morocco', '🇲🇦'),
  Country('Mozambique', '🇲🇿'),
  Country('Myanmar', '🇲🇲'),
  Country('Namibia', '🇳🇦'),
  Country('Nauru', '🇳🇷'),
  Country('Nepal', '🇳🇵'),
  Country('Netherlands', '🇳🇱'),
  Country('New Zealand', '🇳🇿'),
  Country('Nicaragua', '🇳🇮'),
  Country('Niger', '🇳🇪'),
  Country('Nigeria', '🇳🇬'),
  Country('North Macedonia', '🇲🇰'),
  Country('Norway', '🇳🇴'),
  Country('Oman', '🇴🇲'),
  Country('Pakistan', '🇵🇰'),
  Country('Palau', '🇵🇼'),
  Country('Panama', '🇵🇦'),
  Country('Papua New Guinea', '🇵🇬'),
  Country('Paraguay', '🇵🇾'),
  Country('Peru', '🇵🇪'),
  Country('Philippines', '🇵🇭'),
  Country('Poland', '🇵🇱'),
  Country('Portugal', '🇵🇹'),
  Country('Qatar', '🇶🇦'),
  Country('Romania', '🇷🇴'),
  Country('Russia', '🇷🇺'),
  Country('Rwanda', '🇷🇼'),
  Country('Saint Kitts and Nevis', '🇰🇳'),
  Country('Saint Lucia', '🇱🇨'),
  Country('Saint Vincent and the Grenadines', '🇻🇨'),
  Country('Samoa', '🇼🇸'),
  Country('San Marino', '🇸🇲'),
  Country('Sao Tome and Principe', '🇸🇹'),
  Country('Saudi Arabia', '🇸🇦'),
  Country('Senegal', '🇸🇳'),
  Country('Serbia', '🇷🇸'),
  Country('Seychelles', '🇸🇨'),
  Country('Sierra Leone', '🇸🇱'),
  Country('Singapore', '🇸🇬'),
  Country('Slovakia', '🇸🇰'),
  Country('Slovenia', '🇸🇮'),
  Country('Solomon Islands', '🇸🇧'),
  Country('Somalia', '🇸🇴'),
  Country('South Africa', '🇿🇦'),
  Country('South Sudan', '🇸🇸'),
  Country('Spain', '🇪🇸'),
  Country('Sri Lanka', '🇱🇰'),
  Country('Sudan', '🇸🇩'),
  Country('Suriname', '🇸🇷'),
  Country('Sweden', '🇸🇪'),
  Country('Switzerland', '🇨🇭'),
  Country('Syria', '🇸🇾'),
  Country('Taiwan', '🇹🇼'),
  Country('Tajikistan', '🇹🇯'),
  Country('Tanzania', '🇹🇿'),
  Country('Thailand', '🇹🇭'),
  Country('Togo', '🇹🇬'),
  Country('Tonga', '🇹🇴'),
  Country('Trinidad and Tobago', '🇹🇹'),
  Country('Tunisia', '🇹🇳'),
  Country('Turkey', '🇹🇷'),
  Country('Turkmenistan', '🇹🇲'),
  Country('Tuvalu', '🇹🇻'),
  Country('Uganda', '🇺🇬'),
  Country('Ukraine', '🇺🇦'),
  Country('United Arab Emirates', '🇦🇪'),
  Country('United Kingdom', '🇬🇧'),
  Country('United States', '🇺🇸'),
  Country('Uruguay', '🇺🇾'),
  Country('Uzbekistan', '🇺🇿'),
  Country('Vanuatu', '🇻🇺'),
  Country('Vatican City', '🇻🇦'),
  Country('Venezuela', '🇻🇪'),
  Country('Vietnam', '🇻🇳'),
  Country('Yemen', '🇾🇪'),
  Country('Zambia', '🇿🇲'),
  Country('Zimbabwe', '🇿🇼'),
];
